% -------------------------------------------------------------------
%  Generated by MATLAB on 17-Oct-2025 12:21:46
%  MATLAB version: 24.2.0.2712019 (R2024b)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

AllTypemnSet = saveVarsMat.AllTypemnSet; % <684x14 cell> too many elements

clear saveVarsMat;
